controller_list:
  - name: fake_dianaS1_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
initial:  # Define initial robot poses.
  - group: dianaS1_arm
    pose: home